baseURL = 'https://example.org/'
relativeURLs = true
languageCode = 'en-us'
title = 'SWEN-'

cleanDestinationDir = true
minifyOutput = true

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML"]
  section = ["HTML"]
  taxonomy = ["HTML"]
  term = ["HTML"]
  page = ["HTML"]