baseURL = 'https://example.org/'
relativeURLs = true
languageCode = 'en-us'
title = 'build-test'

cleanDestinationDir = true

[outputs]
home = ["HTML"]
section = ["HTML"]
taxonomy = ["HTML"]
term = ["HTML"]
page = ["HTML"]

[markup.goldmark.renderer]
  unsafe = true